apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-06-13T15:19:55Z"
  generation: 1
  labels:
    app: nginxlab
  name: nginxlab
  namespace: default
  resourceVersion: "58643"
  uid: 763bea95-b003-401d-88ab-a0a1c358d45c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginxlab
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginxlab
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
