apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-06-09T16:29:11Z"
  generation: 1
  labels:
    app: nginxsvc
  name: nginxsvc
  namespace: default
  resourceVersion: "35799"
  uid: efb9dadf-cad5-4e50-bbcf-53e5eb621383
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginxsvc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginxsvc
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
